# Generated by Django 5.2.1 on 2025-05-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccioncultivo',
            name='id_seccion',
        ),
        migrations.AddField(
            model_name='seccioncultivo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seccioncultivo',
            name='invernadero',
            field=models.CharField(),
        ),
    ]
