# Generated by Django 5.2.1 on 2025-05-31 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernaderos', '0001_initial'),
        ('secciones', '0002_remove_seccioncultivo_id_seccion_seccioncultivo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccioncultivo',
            name='id',
        ),
        migrations.AddField(
            model_name='seccioncultivo',
            name='id_seccion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seccioncultivo',
            name='invernadero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invernaderos.invernadero'),
        ),
    ]
