# Generated by Django 5.2.1 on 2025-06-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terreno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='propietario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='tamaño',
            field=models.FloatField(help_text='Tamaño del terreno en hectáreas (por ejemplo: 2.5).'),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
    ]
