# Generated by Django 5.2.1 on 2025-06-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terreno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terreno',
            old_name='ubicación',
            new_name='ubicacion',
        ),
    ]
