# Generated by Django 5.2.1 on 2025-06-09 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granos', '0001_initial'),
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='grano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='granos.grano'),
        ),
    ]
