# Generated by Django 5.2.1 on 2025-06-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_grano', models.CharField(choices=[('maiz', 'Maíz'), ('arroz', 'Arroz'), ('trigo', 'Trigo'), ('soya', 'Soya')], max_length=20)),
                ('fecha', models.DateField()),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('impurezas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
