# Generated by Django 5.2.1 on 2025-06-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='configuracion_riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.TimeField()),
                ('hora_inicio', models.TimeField()),
                ('duracion', models.TimeField()),
                ('tipo_riego', models.CharField(max_length=50)),
                ('caudal', models.FloatField()),
                ('presion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='lectura_sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('unidad', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('grados', 'Grados')], default='porcentaje', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='zona_riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=50)),
                ('tipo_planta', models.CharField(max_length=50)),
                ('necesidades_hidricas', models.CharField(max_length=100)),
                ('exposicion_solar', models.CharField(max_length=50)),
            ],
        ),
    ]
