# Generated by Django 5.2.1 on 2025-06-07 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('producto', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
                ('fecha_recepcion', models.DateField()),
                ('peso_total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PruebaCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('impurezas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=100)),
                ('fecha_prueba', models.DateField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.calidad')),
            ],
        ),
    ]
