# Generated by Django 5.2.1 on 2025-06-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requerimiento',
            old_name='Fecha_de_siembra',
            new_name='fecha_de_siembra',
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='tipo_de_terreno',
            field=models.CharField(max_length=100),
        ),
    ]
