# Generated by Django 5.2.1 on 2025-06-03 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernaderos', '0001_initial'),
        ('usuario', '0002_remove_usuario_id_usuario_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invernadero',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
