# Generated by Django 5.2.1 on 2025-05-31 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secciones', '0003_remove_seccioncultivo_id_seccioncultivo_id_seccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sensor', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('intervalo_med', models.IntegerField()),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secciones.seccioncultivo')),
            ],
        ),
    ]
