# Generated by Django 5.2.1 on 2025-05-31 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secciones', '0003_remove_seccioncultivo_id_seccioncultivo_id_seccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuadorRiego',
            fields=[
                ('id_actuador', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_actuador', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_activacion', models.DateTimeField(auto_now=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secciones.seccioncultivo')),
            ],
        ),
    ]
