# Generated by Django 5.2.1 on 2025-06-09 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosechas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reporte',
            new_name='ReporteAlertas',
        ),
        migrations.AlterModelOptions(
            name='configuracionalertas',
            options={'verbose_name': 'Configuración de Alerta', 'verbose_name_plural': 'Configuraciones de Alertas'},
        ),
    ]
