# Generated by Django 5.2.1 on 2025-05-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoteGrano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_grano', models.CharField(choices=[('maiz', 'Maíz'), ('trigo', 'Trigo'), ('soja', 'Soja')], max_length=20)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humedad_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_ingreso', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
