# Generated by Django 5.2.1 on 2025-06-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotegrano',
            name='tipo_grano',
            field=models.CharField(choices=[('maiz', 'maiz'), ('trigo', 'trigo'), ('soja', 'soja')], max_length=20),
        ),
    ]
